# SPDX-FileCopyrightText: 2021 Aaron Dewes
#
# SPDX-License-Identifier: AGPL-3.0-only

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1
metadata:
  category: Wallets
  name: LnMe
  version: 1.4.0
  tagline: Receive tips over Lightning
  description: >-
    This app allows you to receive tips over Lightning.

    You can share the onion address of this app with others and they can dynamically generate an invoice using this app.

    Using some apps, like BlueWallet, users can directly send tips to our Lightning address.

    Your lightning address is <your-name-or-anything-you-like-it-doesn't-matter>@<the-onion-url-of-this-app>.onion.

    If you contact the Citadel team, you can also get a shorter and easier to use @ln.runcitadel.space address. To receive one, contact us on forum.runcitadel.space with your prefered address and also, share the onion URL of the LnMe app (not of your node, the app will have a differen one) or DM us on Twitter (https://twitter.com/runcitadel)
  developer: Michael Bumann
  website: https://ln.michaelbumann.com/
  dependencies:
    - lnd
  repo: https://github.com/bumi/lnme
  support: https://github.com/bumi/lnme/issues
  gallery:
    - https://raw.githubusercontent.com/bumi/lnme/master/lnme-demo.gif
containers:
  - name: web
    image: ghcr.io/bumi/lnme:master@sha256:e131a8584d2b6d1dd01723164cebad0fa2a47b4e30fe0c6fdac83ffb386de518
    port: 1323
    user: 1000:1000
    permissions:
      - lnd
    environment:
      LNME_LND_ADDRESS: $LND_IP:$LND_GRPC_PORT
      LNME_LND_CERT_PATH: /lnd/tls.cert
      LNME_LND_MACAROON_PATH: /lnd/data/chain/bitcoin/$BITCOIN_NETWORK/invoice.macaroon
