# SPDX-FileCopyrightText: 2021 Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1
metadata:
  category: Lightning Node Management
  name: Lightning Shell
  version: 0.1.10
  tagline: Web shell with a selection of LN node management utilities
  description: |-
    This app allows you to access a lot of terminal apps directly on the web.
    The default username for this app is "citadel".
  developer: Ioan Bizău
  website: https://lightningshell.app
  dependencies:
    - lnd
  repo: https://github.com/ibz/lightning-shell
  support: https://github.com/ibz/lightning-shell/issues
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  defaultPassword: $APP_SEED
containers:
  - name: web
    image: ghcr.io/ibz/lightning-shell:v0.1.10@sha256:32a51c16839250829ebbae73b52478ad980f635fc0da2742524ea31300298c14
    restart: on-failure
    stop_grace_period: 1m
    port: 7681
    data:
      - data:/data
    permissions:
      - lnd
    environment:
      APP_PASSWORD: ${APP_SEED}
      USERNAME: citadel
      LND_IP: ${LND_IP}
      LND_GRPC_PORT: ${LND_GRPC_PORT}
